"""Seed demo reports into the Supabase reports table."""
import sys
sys.path.insert(0, ".")
from app.lib.supabase import supabase

seed_data = [
    {
        "report_id": "STR-2026-0041", "type": "STR", "status": "FILED",
        "subject": "Cycle Detected — 4-Node Circular Flow",
        "user_name": "V*** S***", "amount": 385000, "filed_by": "Officer Khan",
        "reg_ref": "FIU/STR/2026/04102",
        "created_at": "2026-02-21T13:58:19Z", "filed_at": "2026-02-21T14:10:00Z",
        "content": (
            "SUSPICIOUS TRANSACTION REPORT\n"
            "Filed under: Prevention of Money Laundering Act 2002\n\n"
            "Report ID: STR-2026-0041\nSubject Account: V*** S***\n"
            "Filed By: Officer Khan\nDate Filed: 2026-02-21 14:10:00\n"
            "FIU Reference: FIU/STR/2026/04102\n\n"
            "NARRATIVE:\nCycle Detected — 4-Node Circular Flow. "
            "Total amount involved: ₹3,85,000.\n"
            "Supporting transaction evidence is attached as Annexure A.\n\n"
            "[DETERMINISTIC — No AI-generated text in this filing]"
        ),
    },
    {
        "report_id": "STR-2026-0040", "type": "STR", "status": "FILED",
        "subject": "Sanctions Match — OFAC Partial Hit",
        "user_name": "A*** O***", "amount": 120000, "filed_by": "Officer Shah",
        "reg_ref": "FIU/STR/2026/04101",
        "created_at": "2026-02-21T12:15:38Z", "filed_at": "2026-02-21T12:30:00Z",
        "content": (
            "SUSPICIOUS TRANSACTION REPORT\n"
            "Filed under: Prevention of Money Laundering Act 2002\n\n"
            "Report ID: STR-2026-0040\nSubject Account: A*** O***\n"
            "Filed By: Officer Shah\nDate Filed: 2026-02-21 12:30:00\n"
            "FIU Reference: FIU/STR/2026/04101\n\n"
            "NARRATIVE:\nSanctions Match — OFAC Partial Hit. "
            "Total amount involved: ₹1,20,000.\n\n"
            "[DETERMINISTIC — No AI-generated text in this filing]"
        ),
    },
    {
        "report_id": "STR-2026-0039", "type": "STR", "status": "PENDING_REVIEW",
        "subject": "Structuring Detected — ML Isolation Forest",
        "user_name": "P*** M***", "amount": 47500, "filed_by": "Officer Shah",
        "created_at": "2026-02-21T14:28:42Z",
        "content": (
            "SUSPICIOUS TRANSACTION REPORT\n"
            "Filed under: Prevention of Money Laundering Act 2002\n\n"
            "Report ID: STR-2026-0039\nSubject Account: P*** M***\n"
            "Status: PENDING FILING\n\n"
            "NARRATIVE:\nStructuring Detected — ML Isolation Forest. "
            "Total amount involved: ₹47,500.\n\n"
            "[DETERMINISTIC — No AI-generated text in this filing]"
        ),
    },
    {
        "report_id": "CTR-2026-0112", "type": "CTR", "status": "FILED",
        "subject": "Mandatory CTR — Monthly Cash Exceeds ₹10L",
        "user_name": "R*** K***", "amount": 1245000, "filed_by": "System",
        "reg_ref": "FIU/CTR/2026/01120",
        "created_at": "2026-02-20T16:00:00Z", "filed_at": "2026-02-20T16:00:00Z",
        "content": (
            "CASH TRANSACTION REPORT\n"
            "Mandatory filing under PMLA 2002, Rule 3\n\n"
            "Report ID: CTR-2026-0112\nAccount: R*** K***\n"
            "Total Cash Transactions: ₹12,45,000\n"
            "Threshold: ₹10,00,000\n"
            "FIU Reference: FIU/CTR/2026/01120\n\n"
            "This CTR was auto-generated by the Sentinel compliance platform.\n"
            "Mandatory reporting — no officer discretion required."
        ),
    },
    {
        "report_id": "CTR-2026-0111", "type": "CTR", "status": "FILED",
        "subject": "Mandatory CTR — Monthly Cash Exceeds ₹10L",
        "user_name": "D*** J***", "amount": 1080000, "filed_by": "System",
        "reg_ref": "FIU/CTR/2026/01119",
        "created_at": "2026-02-19T16:00:00Z", "filed_at": "2026-02-19T16:00:00Z",
        "content": (
            "CASH TRANSACTION REPORT\n"
            "Mandatory filing under PMLA 2002, Rule 3\n\n"
            "Report ID: CTR-2026-0111\nAccount: D*** J***\n"
            "Total Cash Transactions: ₹10,80,000\n"
            "Threshold: ₹10,00,000\n"
            "FIU Reference: FIU/CTR/2026/01119\n\n"
            "This CTR was auto-generated by the Sentinel compliance platform."
        ),
    },
    {
        "report_id": "INT-2026-0018", "type": "INTERNAL", "status": "DRAFT",
        "subject": "AI Override Investigation — Student Account Surge",
        "user_name": "S*** F***", "amount": 750000, "filed_by": "Officer Shah",
        "created_at": "2026-02-21T14:15:33Z",
        "content": (
            "INTERNAL INVESTIGATION REPORT\n"
            "Report ID: INT-2026-0018\nSubject: S*** F***\n"
            "Investigator: Officer Shah\n\n"
            "Summary: AI Override Investigation — Student Account Surge\n"
            "Amount under review: ₹7,50,000\n\n"
            "[INTERNAL USE ONLY — NOT FOR REGULATORY FILING]"
        ),
    },
    {
        "report_id": "STR-2026-0038", "type": "STR", "status": "REJECTED",
        "subject": "Dormant Account Reactivation",
        "user_name": "M*** D***", "amount": 215000, "filed_by": "Officer Patel",
        "created_at": "2026-02-18T09:20:00Z",
        "content": (
            "SUSPICIOUS TRANSACTION REPORT\n"
            "Filed under: Prevention of Money Laundering Act 2002\n\n"
            "Report ID: STR-2026-0038\nSubject Account: M*** D***\n"
            "Status: REJECTED\n\n"
            "NARRATIVE:\nDormant Account Reactivation. "
            "Total amount involved: ₹2,15,000.\n\n"
            "[DETERMINISTIC — No AI-generated text in this filing]"
        ),
    },
    {
        "report_id": "INT-2026-0017", "type": "INTERNAL", "status": "FILED",
        "subject": "Geo-Velocity Anomaly — Cross-Border Review",
        "user_name": "N*** R***", "amount": 540000, "filed_by": "Officer Khan",
        "created_at": "2026-02-17T11:30:00Z", "filed_at": "2026-02-17T14:00:00Z",
        "content": (
            "INTERNAL INVESTIGATION REPORT\n"
            "Report ID: INT-2026-0017\nSubject: N*** R***\n"
            "Investigator: Officer Khan\n\n"
            "Summary: Geo-Velocity Anomaly — Cross-Border Review\n"
            "Amount under review: ₹5,40,000\n\n"
            "[INTERNAL USE ONLY — NOT FOR REGULATORY FILING]"
        ),
    },
]

res = supabase.table("reports").insert(seed_data).execute()
print(f"Seeded {len(res.data)} reports successfully!")
for r in res.data:
    print(f"  {r['report_id']} - {r['type']} - {r['status']}")
