"""
Deterministic alert explanation templates — no LLM, no hallucination.
From Features of Sentinel.md, Module 3, Section 3.3.

Every alert explanation is generated from verified data templates,
not LLM inference.
"""

import json


ALERT_TEMPLATES = {
    "CYCLE_DETECTED": (
        "Graph analysis detected a {hop_count}-node transaction cycle: "
        "{cycle_path}. Total amount transferred through cycle: ₹{total_amount:,.0f}. "
        "Cycle completed within {window_hours} hours. "
        "This pattern is consistent with potential layering activity."
    ),
    "ANOMALY_AMOUNT": (
        "Transaction of ₹{txn_amount:,.0f} is {zscore:.1f} standard deviations "
        "above the user's 90-day average of ₹{user_avg:,.0f}. "
        "Statistical anomaly detected by Isolation Forest model "
        "(anomaly score: {anomaly_score:.2f})."
    ),
    "CTR_THRESHOLD": (
        "Cash transactions for account {account_id} totaled ₹{total:,.0f} "
        "this month, exceeding the ₹10,00,000 CTR reporting threshold. "
        "Mandatory FIU-IND Cash Transaction Report required under "
        "PMLA 2002, Rule 3."
    ),
    "SANCTIONS_HIT": (
        "Name '{input_name}' (normalized: '{normalized_name}') matched "
        "against {list_name} entry '{matched_name}' with similarity score "
        "{score:.1%}. Source: {source}. Match date: {match_date}."
    ),
    "FAN_IN_FAN_OUT": (
        "Account received {in_count} transfers from {in_unique} unique sources "
        "totaling ₹{in_total:,.0f} within {in_window} hours, "
        "then sent {out_count} transfers to {out_unique} unique destinations "
        "totaling ₹{out_total:,.0f} within {out_window} hours. "
        "Fan-in/Fan-out ratio: {ratio:.1f}. Pattern consistent with "
        "potential mule account activity."
    ),
    "STRUCTURING": (
        "Multiple transactions individually below ₹{threshold:,.0f} reporting "
        "threshold detected: {count} transactions totaling ₹{total:,.0f} "
        "within {window_hours} hours. Average transaction: ₹{avg_amount:,.0f}. "
        "This pattern is consistent with Rule #{rule_id} (Structuring/Smurfing Detection)."
    ),
    "GEO_VELOCITY": (
        "Transaction originated from {location_a}, {distance_km:.0f} km "
        "from previous transaction location ({location_b}). "
        "Time between transactions: {time_gap_minutes:.0f} minutes. "
        "Required travel speed: {required_speed_kmh:.0f} km/h — "
        "physically impossible, indicating potential account compromise."
    ),
}


# ─── STR report narratives (per-rule) ───────────────────────────────

STR_RULE_NARRATIVES = {
    "STRUCTURING": (
        "Each transaction was individually below the ₹{threshold:,.0f} "
        "reporting threshold. This pattern is consistent with Rule "
        "#{rule_id} (Structuring/Smurfing Detection)."
    ),
    "CYCLE": (
        "A circular fund flow was identified involving {hop_count} accounts: "
        "{cycle_path}. The cycle completed within {window_hours} hours."
    ),
    "SANCTIONS": (
        "The subject's name matched entry '{matched_name}' on the "
        "{list_name} with {score:.1%} similarity."
    ),
    "FAN_IN_FAN_OUT": (
        "The account exhibited mule-like behaviour: {in_count} inflows from "
        "{in_unique} sources (₹{in_total:,.0f}) followed by {out_count} outflows "
        "to {out_unique} destinations (₹{out_total:,.0f})."
    ),
}


# ─── Main entry point ───────────────────────────────────────────────

def generate_deterministic_explanation(alert_type: str, evidence: dict) -> str:
    """
    Generates alert explanation from templates + verified evidence.
    No LLM. No hallucination. No liability.
    """
    template = ALERT_TEMPLATES.get(alert_type)
    if not template:
        return f"Alert type: {alert_type}. Evidence: {json.dumps(evidence, default=str)}"
    try:
        return template.format(**evidence)
    except KeyError as e:
        return f"Alert type: {alert_type}. Missing evidence field: {e}. Raw: {json.dumps(evidence, default=str)}"


def generate_str_narrative(alert: dict) -> str:
    """
    Deterministic STR narrative generation.
    'No creativity. No hallucination. No lawsuit.' — Roast v2, Critical 2
    """
    base_template = (
        "Between {start_date} and {end_date}, the subject account "
        "(ID: {account_id}) executed {count} transaction(s) totaling "
        "₹{total_amount:,.0f}. "
        "{rule_specific_narrative} "
        "Supporting transaction evidence is attached as Annexure A. "
        "This report was generated by the Sentinel compliance platform "
        "and reviewed by {officer_name} (ID: {officer_id}) on {review_date}."
    )

    primary_rule = alert.get("primary_rule", "")
    rule_template = STR_RULE_NARRATIVES.get(primary_rule, "")

    try:
        alert["rule_specific_narrative"] = rule_template.format(**alert) if rule_template else ""
    except KeyError:
        alert["rule_specific_narrative"] = ""

    try:
        return base_template.format(**alert)
    except KeyError as e:
        return f"STR narrative generation failed — missing field: {e}"


def generate_ctr_narrative(evidence: dict) -> str:
    """
    Deterministic CTR narrative generation.
    """
    template = (
        "Cash transactions for account {account_id} totaled ₹{total:,.0f} "
        "during the reporting period ({start_date} to {end_date}). "
        "This exceeds the ₹10,00,000 Cash Transaction Report threshold "
        "mandated under PMLA 2002, Rule 3. "
        "{count} individual cash transaction(s) were recorded. "
        "This report was generated by the Sentinel compliance platform "
        "and reviewed by {officer_name} (ID: {officer_id}) on {review_date}. "
        "Supporting transaction evidence is attached as Annexure A."
    )
    try:
        return template.format(**evidence)
    except KeyError as e:
        return f"CTR narrative generation failed — missing field: {e}"
