from fastapi import APIRouter, Depends, HTTPException, Query, status
from typing import Dict, Optional, List
from pydantic import BaseModel
from app.api.dependencies import require_role, get_optional_user
from app.lib.supabase import supabase
from datetime import datetime

router = APIRouter(prefix="/api/reports", tags=["Reports"])


# ─── Request / Response Models ──────────────────────────────────────

class CreateReportRequest(BaseModel):
    type: str  # STR | CTR | INTERNAL
    subject: str
    user_name: str = ""
    user_id: Optional[str] = None
    amount: float = 0
    filed_by: str = "System"
    content: Optional[str] = None
    alert_id: Optional[str] = None


class UpdateStatusRequest(BaseModel):
    status: str  # DRAFT | PENDING_REVIEW | FILED | REJECTED


class STRRequest(BaseModel):
    alert_id: str


class CTRRequest(BaseModel):
    account_id: str
    start_date: str
    end_date: str


# ─── Helper: generate next report_id ────────────────────────────────

def _next_report_id(report_type: str) -> str:
    """Generate the next sequential report_id like STR-2026-0042."""
    prefix_map = {"STR": "STR", "CTR": "CTR", "INTERNAL": "INT"}
    prefix = prefix_map.get(report_type, "RPT")
    year = datetime.utcnow().strftime("%Y")

    try:
        res = (
            supabase.table("reports")
            .select("report_id")
            .like("report_id", f"{prefix}-{year}-%")
            .execute()
        )
        if res.data:
            max_num = 0
            for row in res.data:
                try:
                    num = int(row["report_id"].split("-")[-1])
                    if num > max_num:
                        max_num = num
                except (ValueError, IndexError):
                    pass
            return f"{prefix}-{year}-{str(max_num + 1).zfill(4)}"
    except Exception:
        pass

    return f"{prefix}-{year}-0001"


# ─── Helper: generate deterministic content ─────────────────────────

def _generate_content(report_type: str, subject: str, user_name: str, amount: float, filed_by: str, report_id: str) -> str:
    """Generate deterministic report content from a template."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    amt_str = f"₹{amount:,.0f}"

    if report_type == "STR":
        return (
            f"SUSPICIOUS TRANSACTION REPORT\n"
            f"Filed under: Prevention of Money Laundering Act 2002\n\n"
            f"Report ID: {report_id}\n"
            f"Subject Account: {user_name}\n"
            f"Filed By: {filed_by}\n"
            f"Date Created: {now}\n"
            f"Status: DRAFT\n\n"
            f"NARRATIVE:\n{subject}. Total amount involved: {amt_str}.\n"
            f"Supporting transaction evidence is attached as Annexure A.\n"
            f"This report was generated by the Sentinel compliance platform\n"
            f"and prepared by {filed_by} on {now}.\n\n"
            f"[DETERMINISTIC — No AI-generated text in this filing]"
        )
    elif report_type == "CTR":
        return (
            f"CASH TRANSACTION REPORT\n"
            f"Mandatory filing under PMLA 2002, Rule 3\n\n"
            f"Report ID: {report_id}\n"
            f"Account: {user_name}\n"
            f"Total Cash Transactions: {amt_str}\n"
            f"Threshold: ₹10,00,000\n\n"
            f"This CTR was auto-generated by the Sentinel compliance platform.\n"
            f"Mandatory reporting — no officer discretion required."
        )
    else:
        return (
            f"INTERNAL INVESTIGATION REPORT\n"
            f"Report ID: {report_id}\n"
            f"Subject: {user_name}\n"
            f"Investigator: {filed_by}\n"
            f"Created: {now}\n\n"
            f"Summary: {subject}\n"
            f"Amount under review: {amt_str}\n\n"
            f"[INTERNAL USE ONLY — NOT FOR REGULATORY FILING]"
        )


# ═══════════════════════════════════════════════════════════════════════
#  GET /api/reports — List all reports
# ═══════════════════════════════════════════════════════════════════════

@router.get("")
async def list_reports(
    type: Optional[str] = Query(None, description="Filter by type: STR, CTR, INTERNAL"),
    report_status: Optional[str] = Query(None, alias="status", description="Filter by status"),
    search: Optional[str] = Query(None, description="Search in report_id, subject, user_name"),
    limit: int = Query(100, le=500),
    current_user: Dict[str, str] = Depends(get_optional_user),
):
    """List all reports with optional filtering."""
    try:
        query = supabase.table("reports").select("*").order("created_at", desc=True).limit(limit)

        if type:
            query = query.eq("type", type.upper())
        if report_status:
            query = query.eq("status", report_status.upper())

        res = query.execute()
        reports = res.data or []

        # Client-side search filter (Supabase free tier doesn't support full-text easily)
        if search:
            q = search.lower()
            reports = [
                r for r in reports
                if q in (r.get("report_id", "")).lower()
                or q in (r.get("subject", "")).lower()
                or q in (r.get("user_name", "")).lower()
            ]

        # Compute stats
        all_reports = supabase.table("reports").select("type, status").execute().data or []
        str_filed = sum(1 for r in all_reports if r["type"] == "STR" and r["status"] == "FILED")
        ctr_filed = sum(1 for r in all_reports if r["type"] == "CTR" and r["status"] == "FILED")
        pending = sum(1 for r in all_reports if r["status"] in ("PENDING_REVIEW", "DRAFT"))

        return {
            "reports": reports,
            "stats": {
                "str_filed": str_filed,
                "ctr_filed": ctr_filed,
                "pending": pending,
                "total": len(all_reports),
            },
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch reports: {str(e)}")


# ═══════════════════════════════════════════════════════════════════════
#  POST /api/reports/create — Create a new report
# ═══════════════════════════════════════════════════════════════════════

@router.post("/create")
async def create_report(
    req: CreateReportRequest,
    current_user: Dict[str, str] = Depends(get_optional_user),
):
    """Create a new STR/CTR/INTERNAL report."""
    if req.type not in ("STR", "CTR", "INTERNAL"):
        raise HTTPException(status_code=400, detail="type must be STR, CTR, or INTERNAL")

    report_id = _next_report_id(req.type)
    content = req.content or _generate_content(
        req.type, req.subject, req.user_name, req.amount, req.filed_by, report_id
    )

    entry = {
        "report_id": report_id,
        "type": req.type,
        "status": "DRAFT",
        "subject": req.subject,
        "user_name": req.user_name,
        "user_id": req.user_id,
        "amount": req.amount,
        "filed_by": req.filed_by,
        "content": content,
        "alert_id": req.alert_id,
        "created_at": datetime.utcnow().isoformat(),
    }

    try:
        res = supabase.table("reports").insert(entry).execute()
        return res.data[0] if res.data else entry
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create report: {str(e)}")


# ═══════════════════════════════════════════════════════════════════════
#  PATCH /api/reports/{report_id}/status — Update report status
# ═══════════════════════════════════════════════════════════════════════

@router.patch("/{report_id}/status")
async def update_report_status(
    report_id: str,
    req: UpdateStatusRequest,
    current_user: Dict[str, str] = Depends(get_optional_user),
):
    """Update a report's status (e.g., DRAFT → PENDING_REVIEW → FILED)."""
    if req.status not in ("DRAFT", "PENDING_REVIEW", "FILED", "REJECTED"):
        raise HTTPException(status_code=400, detail="Invalid status")

    update_data = {"status": req.status}
    if req.status == "FILED":
        update_data["filed_at"] = datetime.utcnow().isoformat()

    try:
        res = (
            supabase.table("reports")
            .update(update_data)
            .eq("report_id", report_id)
            .execute()
        )
        if not res.data:
            raise HTTPException(status_code=404, detail="Report not found")
        return res.data[0]
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update report: {str(e)}")


# ═══════════════════════════════════════════════════════════════════════
#  GET /api/reports/{report_id} — Get single report
# ═══════════════════════════════════════════════════════════════════════

@router.get("/{report_id}")
async def get_report(
    report_id: str,
    current_user: Dict[str, str] = Depends(get_optional_user),
):
    """Get a single report by its report_id."""
    try:
        res = supabase.table("reports").select("*").eq("report_id", report_id).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Report not found")
        return res.data[0]
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ═══════════════════════════════════════════════════════════════════════
#  Legacy endpoints: POST /api/reports/str and /api/reports/ctr
#  (kept for backward compat with alert-driven report generation)
# ═══════════════════════════════════════════════════════════════════════

@router.post("/str")
async def generate_str_report(
    req: STRRequest,
    current_user: Dict[str, str] = Depends(require_role("officer", "admin")),
):
    """Generate a Suspicious Transaction Report (STR) from an alert."""
    from app.engine.alert_templates import generate_str_narrative

    alert_res = supabase.table("alerts").select("*").eq("id", req.alert_id).single().execute()
    if not alert_res.data:
        raise HTTPException(status_code=404, detail="Alert not found")
    alert = alert_res.data

    if alert["status"] == "FILED_STR":
        raise HTTPException(status_code=400, detail="STR already filed for this alert")

    evidence = alert.get("evidence", {})
    sus_txs = evidence.get("suspicious_transactions", [])

    if not sus_txs:
        start_date, end_date, count, total_amount = "UNKNOWN", "UNKNOWN", 0, 0.0
        account_id = alert.get("user_id", "UNKNOWN")
    else:
        sorted_txs = sorted(sus_txs, key=lambda x: x["timestamp"])
        start_date, end_date = sorted_txs[0]["timestamp"], sorted_txs[-1]["timestamp"]
        count = len(sus_txs)
        total_amount = sum(t["amount"] for t in sus_txs)
        account_id = alert.get("user_id")

    narrative_data = {
        "start_date": start_date, "end_date": end_date,
        "account_id": account_id, "count": count, "total_amount": total_amount,
        "primary_rule": alert.get("rule_name", "UNKNOWN"),
        "rule_id": alert.get("rule_id", "UNKNOWN"),
        "threshold": evidence.get("threshold_used", 1000000),
        "officer_name": current_user.get("email", "Unknown Officer"),
        "officer_id": current_user["user_id"],
        "review_date": datetime.utcnow().strftime("%Y-%m-%d"),
    }
    narrative_data.update(evidence)
    report_text = generate_str_narrative(narrative_data)

    report_id = _next_report_id("STR")
    report_entry = {
        "report_id": report_id,
        "alert_id": req.alert_id,
        "type": "STR",
        "generated_by": current_user["user_id"],
        "filed_by": current_user.get("email", "Unknown"),
        "content": report_text,
        "status": "DRAFT",
        "subject": f"STR from Alert {req.alert_id}",
        "user_name": account_id or "Unknown",
        "amount": total_amount,
        "created_at": datetime.utcnow().isoformat(),
    }

    try:
        rep_res = supabase.table("reports").insert(report_entry).execute()
    except Exception as e:
        print(f"Failed to save report: {e}")
        rep_res = type("obj", (object,), {"data": [report_entry]})

    supabase.table("alerts").update({"status": "FILED_STR"}).eq("id", req.alert_id).execute()

    try:
        supabase.table("compliance_audit_logs").insert({
            "user_id": alert.get("user_id", "UNKNOWN"),
            "action": "STR_FILED",
            "performed_by": current_user["user_id"],
            "evidence": {"report_content_snippet": report_text[:200]},
            "timestamp": datetime.utcnow().isoformat(),
            "previous_hash": "STR_EVENT",
            "record_hash": "STR_EVENT",
        }).execute()
    except Exception:
        pass

    return rep_res.data[0]


@router.post("/ctr")
async def generate_ctr_report(
    req: CTRRequest,
    current_user: Dict[str, str] = Depends(require_role("officer", "admin")),
):
    """Generate a Cash Transaction Report (CTR) using a deterministic template."""
    from app.engine.alert_templates import generate_ctr_narrative

    try:
        tx_res = (
            supabase.table("transactions")
            .select("*")
            .eq("user_id", req.account_id)
            .gte("created_at", req.start_date)
            .lte("created_at", req.end_date)
            .limit(1000)
            .execute()
        )
        transactions = tx_res.data or []
    except Exception:
        transactions = []

    count = len(transactions)
    total = sum(t.get("amount", 0) for t in transactions)

    narrative_data = {
        "account_id": req.account_id,
        "total": total,
        "start_date": req.start_date,
        "end_date": req.end_date,
        "count": count,
        "officer_name": current_user.get("email", "Unknown Officer"),
        "officer_id": current_user["user_id"],
        "review_date": datetime.utcnow().strftime("%Y-%m-%d"),
    }
    report_text = generate_ctr_narrative(narrative_data)

    report_id = _next_report_id("CTR")
    report_entry = {
        "report_id": report_id,
        "type": "CTR",
        "filed_by": current_user.get("email", "Unknown"),
        "content": report_text,
        "status": "DRAFT",
        "subject": f"CTR for account {req.account_id}",
        "user_name": req.account_id,
        "amount": total,
        "created_at": datetime.utcnow().isoformat(),
    }

    try:
        rep_res = supabase.table("reports").insert(report_entry).execute()
    except Exception:
        rep_res = type("obj", (object,), {"data": [report_entry]})

    try:
        supabase.table("compliance_audit_logs").insert({
            "user_id": req.account_id,
            "action": "CTR_FILED",
            "performed_by": current_user["user_id"],
            "evidence": {"total": total, "count": count},
            "timestamp": datetime.utcnow().isoformat(),
            "previous_hash": "CTR_EVENT",
            "record_hash": "CTR_EVENT",
        }).execute()
    except Exception:
        pass

    return rep_res.data[0]
